### ISSUE TITLE
Nitroflare lookup never returns

### ISSUE THREAD

**Issue by sjonez** [Thomanphan/urlchecker#12]
Is there a problem checking files on nitroflare.com?

For example, enter http://nitroflare.com/view/6FBD8D633B3304D/1118725107.pdf in the checker and it just sits there seemingly forever without returning a response. I've tested with working and not-working files with the same result

**Comment by Thomanphan** [comment]
Hello
Issue from my hosting provider. I have moved to new VPS and issue has fixed
