### ISSUE TITLE
easybytez

### ISSUE THREAD

**Issue by aris08** [Thomanphan/urlchecker#13]
hello easybytez download links is not supported any more ?

**Comment by Thomanphan** [comment]
Can you send me a link ?

**Comment by aris08** [comment]
| http://www.easybytez.com/493mafar6rj2
http://www.easybytez.com/tu6pp6sotcx1
http://www.easybytez.com/fws6pm34sb3q
http://www.easybytez.com/oj7gj8n1wl3g
http://www.easybytez.com/1fcuhj5o5xzm |

 

    Στις 7:12 μ.μ. Παρασκευή, 29 Σεπτεμβρίου 2017, ο/η Thomanphan <notifications@github.com> έγραψε:
 

 Can you send me a link ?—

**Comment by Thomanphan** [comment]
Hello
Issue from my hosting provider. I have moved to new VPS and issue has fixed

**Comment by aris08** [comment]
Thank you!!
