### ISSUE TITLE
Link not support

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#16]
Hello

We receive a link not support status for the following url, could you add these to your service please

turbobit.net/q8msllp8mz72.html -> Down/Inactive
turbobit.net/hgphbbqndt5e.html -> Down/Inactive

Thanks
Nick.

**Comment by smowtion** [comment]
Please recheck. turbobit is working normal

**Comment by smowtion** [comment]
hello @hurtn , Can you send me logs id and link not working ?

**Comment by hurtn** [comment]
Hello Thoman, it was #17 I wanted to re-open, there were other links such
as the one below which were active

m.waploaded.com/music/uploads/2016/09/%5bWaploaded%5dDavido_-*Gbagbe_Oshi*
(Prod_By_Shizzi)-1475238872.mp3

I get the following response from the API

{"link":"http:\/\/m.waploaded.com\/music\/uploads\/2016\/09\/[Waploaded]Davido_-_Gbagbe_Oshi_(Prod_By_Shizzi)-1475238872.mp3","result":"Success","api_id":"5a5c8950b3fdb1516013904","status":"dead","api_query":"","daily_limited":"60000","api_member_pack":"Gold
member","current_api_version":"3.1","item":[null]}
