### ISSUE TITLE
add waploaded.com to link checker API

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#17]
Hello, please could you add waploaded.com to check the dead/alive status. Here are some examples

www.waploaded.com/music/melissa-steel-burning-down-ft-wizkid-f4745
www.waploaded.com/music/uploads/2014/08/Eminem_-_Eminem_-_Guts_Over_Fear_(ft._SIA)_(Waploaded.com).mp3
www.waploaded.com/music/lil-wayne-we-alright-ft-birdman-euro-f1715
www.waploaded.com/storage/music/[Waploaded.com]-Lil-Wayne-Krazy.mp3
www.waploaded.com/storage/music/[Waploaded.com]-Wale-Keep-The-Hustle.mp3

Thanks

**Comment by hurtn** [comment]
Good morning, do you have an update on this one?

**Comment by smowtion** [comment]
Hello @hurtn . waploaded has added

**Comment by hurtn** [comment]
thank you very much!

**Comment by hurtn** [comment]
Hello Thoman, we found one link which provides a down/dead status when the link is active.

m.waploaded.com/music/uploads/2016/09/%5bWaploaded%5dDavido_-_Gbagbe_Oshi_(Prod_By_Shizzi)-1475238872.mp3

Thanks
Nick.

**Comment by hurtn** [comment]
Please re-open I have added a new issue to #17

Thank you 
Nick

**Comment by hurtn** [comment]
Hello, copied my message from #16 

m.waploaded.com/music/uploads/2016/09/%5bWaploaded%5dDavido_-*Gbagbe_Oshi*
(Prod_By_Shizzi)-1475238872.mp3

I get the following response from the API

{"link":"http:\/\/m.waploaded.com\/music\/uploads\/2016\/09\/[Waploaded]Davido_-_Gbagbe_Oshi_(Prod_By_Shizzi)-1475238872.mp3","result":"Success","api_id":"5a5c8950b3fdb1516013904","status":"dead","api_query":"","daily_limited":"60000","api_member_pack":"Gold
member","current_api_version":"3.1","item":[null]}

Thanks
Nick.

**Comment by hurtn** [comment]
Hello, please let me know if you have any updates...
Thanks

**Comment by smowtion** [comment]
Hello
I checked and 404 Not Found this file
<img width="935" alt="screen shot 2018-01-23 at 20 49 33" src="https://user-images.githubusercontent.com/1168604/35279217-00a33b1c-007f-11e8-836e-58f9848a429e.png">
Please recheck
