### ISSUE TITLE
support for dopefile.pk

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#19]
Hello please add link status support for dopefile.pk Here are some examples

dopefile.pk/8ezenvo58ugm - ACTIVE
dopefile.pk/fyphozhyk1lc - DOWN
dopefile.pk/mp3embed-2ociodx6e924.mp3 - UNKNOWN
dopefile.pk/embed/v1/darkplayer.php?c=7m58eadmehxv&amp;b1=0098da&amp;bg=2B2B2B&amp;p=5CBEC9&amp;t=Florida Georgia Line &ndash; Smooth.mp3 - UNKNOWN

Thanks
Nick.

**Comment by smowtion** [comment]
Done
