### ISSUE TITLE
Please add support for bajalo.org

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#21]
examples: 

bajalo.org/audios/down.php?file=Becky%20G%20Ft.%20Justin%20Quiles%20-%20Todo%20Cambio%20Remix.mp3&id=5687
bajalo.org/audios/down.php?file=Drake%20Ft.%20Young%20Thug%20-%20Ice%20Melts.mp3&id=6684

This url returned a ERROR: Resp Code - 503

bajalo.org/audios/down.php?file=Alessia%20Cara%20-%20Scars%20To%20Your%20Beautiful.mp3&id=3732

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
This site can’t be reached
bajalo.org took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Network Diagnostics
ERR_CONNECTION_TIMED_OUT
