### ISSUE TITLE
Please add support for dirrtyshar.es

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#22]
Examples
www.dirrtyshar.es/1f0adf606fc1bdd2?pt=0EruAcW0W%2FiZxQ3VX5fkJgzoMZyAalUJFrjSUdYaEDo%3D&pg=2
www.dirrtyshar.es/a9028a79d0ef76a5?pt=6LQnHTiSvmXrwoprJGDpQGOEECQm784%2FhieiM7haGMY%3D&pg=2

This url returned ERROR: Resp Code - 503
www.dirrtyshar.es/d1af3c089e8656ed?pt=yVMraOW6I7NXmqnolGc3vBV9SFFt6Ck5A8m%2B2Cg0LPc%3D&pg=2

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
Done
