### ISSUE TITLE
Please add support for kiwi6.com

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#23]
Examples
kiwi6.com/file/or02alpbgx/embed_designer
kiwi6.com/file/zi70ostm6q
kiwi6.com/file/3pc044xu8w
k003.kiwi6.com/hotlink/mcjjeypiks/Diplo_-_Bankroll_Ft_Justin_Bieber_Young_Thug_Rich_the_Kid_www.mpnaija.com.mp3

The following returned a ERROR: Resp Code - 503

kiwi6.com/file/02nzaawruk

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
kiwi6.com/file/* has added to URLC but Can't add hotlink to URLC. Give me live link

**Comment by Ktaggar** [comment]
https://kiwi6.com/artists/kristijanfaust/snowfall
https://kiwi6.com/artists/MarekIwaszkiewicz/fragile

thank you

**Comment by smowtion** [comment]
Download link file : https://k002.kiwi6.com/download/7c4qlni3c4 not like you link give me k003.kiwi6.com/hotlink/mcjjeypiks/Diplo_-_Bankroll_Ft_Justin_Bieber_Young_Thug_Rich_

**Comment by Ktaggar** [comment]
https://k006.kiwi6.com/download/89egzfld8n

is that link ok?

**Comment by Ktaggar** [comment]
http://k006.kiwi6.com/hotlink/89egzfld8n/Fragile.mp3

**Comment by Ktaggar** [comment]
Hi

Was this link ok or did you require another

thank you
