### ISSUE TITLE
Please add support for myupload.space

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#24]
Examples:
myupload.space/s.php?f=baixar20IQtVTJKr6f
myupload.space/s.php?f=baixar3791KMHRBQnW
myupload.space/file.php?folder=/&file=baixar25I50DYX7SwG
myupload.space/s.php?f=baixar21auxrztcnpH
myupload.space/file.php?folder=/&file=baixar23xIwgPuuKwh

The following url returned a ERROR: Resp Code - 503
myupload.space/s.php?f=baixar20G0DDiv2l84

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
Website has down. 
http://prntscr.com/i4eo8b
