### ISSUE TITLE
Please add support for omerta.is

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#25]
Examples
omerta.is/2j2H
omerta.is/109u?pt=Q8z0m9zzno4hU0DJSr4vBaT%2FwgF0oZBd24NBEDtF8Q8%3D
omerta.is/Biz
omerta.is/2jVv
omerta.is/Z8y

The following returned ERROR: Resp Code - 503
omerta.is/Eia?dl=PPZBeYJC

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
Done
