### ISSUE TITLE
Please add support for tunescoop.com

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#26]
Examples
new.tunescoop.com/play/3734343434/skrillex-ruffneck-full-flex-remix-mp3
new.tunescoop.com/search/Little%2520Matador%2520Stitch%2520Yourself%2520Up/
www.tunescoop.com/play/343331373738/broiler-amazing-feat-kurt-nilsen-extended-mix-mp3
www.tunescoop.com/play/343338333238/axwell-ingrosso-how-do-you-feel-right-now-original-mix-universal-music-mp3
www.tunescoop.com/play/343239393838/david-guetta-robin-schulz-cheat-codes-shed-a-light-aligee-remix-tonspiel-mp3

The following returned ERROR: Resp Code - 503
www.tunescoop.com/play/343337363538/lika-morgan-feel-the-same-esquires-so-powerful-remix-wwwlivingelectrocom-mp3

**Comment by Ktaggar** [comment]
Hi

Has there been any update on this

thank you

**Comment by smowtion** [comment]
Done @Ktaggar
