### ISSUE TITLE
Please add support for albumkings.org

### ISSUE THREAD

**Issue by Ktaggar** [Thomanphan/urlchecker#27]
Examples:

www.albumkings.org/albums/10041-keyshia-cole-1111-reset-2017/keyshiacole-unbothered
www.albumkings.org/albums/10042-pentatonix-a-pentatonix-christmas-2017/pentatonix-deckthehalls
www.albumkings.org/albums/9790-rick-ross-rather-you-than-me/deadpresidentsfeatfuturejeezyyogotti
www.albumkings.org/albums/10053-dvbbs-blood-of-my-blood-2017

**Comment by smowtion** [comment]
Done

**Comment by Ktaggar** [comment]
www.albumkings.org/albums/5140-temple-by-matthew-the-atlas#startPlayer
www.albumkings.org/albums/5101-sremmlife-2-by-rae-sremmurd#startPlayer
www.albumkings.org/albums/5168-views-by-drake#startPlayer

Status is showing down, but they are still active
