### ISSUE TITLE
issue with waploaded in status check API

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#28]
Hello

Please could you investigate an incorrect status with waploaded. The following link is accessible 

m.waploaded.com/music/uploads/2016/09/%5bWaploaded%5dDavido_-*Gbagbe_Oshi*
(Prod_By_Shizzi)-1475238872.mp3

I get the following response from the API

{"link":"http:\/\/m.waploaded.com\/music\/uploads\/2016\/09\/[Waploaded]Davido_-_Gbagbe_Oshi_(Prod_By_Shizzi)-1475238872.mp3","result":"Success","api_id":"5a5c8950b3fdb1516013904","status":"dead","api_query":"","daily_limited":"60000","api_member_pack":"Gold
member","current_api_version":"3.1","item":[null]}

Thank you

**Comment by smowtion** [comment]
File not found http://prntscr.com/i4flo6

**Comment by hurtn** [comment]
Sorry I'm not sure what you mean, can you explain this post above... the link provided does vend an mp3 download

m.waploaded.com/music/uploads/2016/09/%5bWaploaded%5dDavido_-_Gbagbe_Oshi_(Prod_By_Shizzi)-1475238872.mp3

The API returns dead

**Comment by smowtion** [comment]
It's mean. API working normal. this files is deaded
