### ISSUE TITLE
albumkings.org incorrect status

### ISSUE THREAD

**Issue by Ktaggar** [Thomanphan/urlchecker#30]
www.albumkings.org/albums/5140-temple-by-matthew-the-atlas#startPlayer
www.albumkings.org/albums/5101-sremmlife-2-by-rae-sremmurd#startPlayer
www.albumkings.org/albums/5168-views-by-drake#startPlayer

Status is showing down, but they are still active

**Comment by smowtion** [comment]
Website down right now. Can you send with api_id

**Comment by hurtn** [comment]
Ok I am happy to close this ticket. Thanks
