### ISSUE TITLE
twitter status incorrect

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#31]
Hello 
for suspended accounts the API returns unstatus

request:
http://api5.urlchecker.org/v3/?key=api_key&response_format=json&link=
twitter.com/HipHopKray/statuses/956826525801828354
response:
{"link":"http:\/\/twitter.com\/HipHopKray\/statuses\/956826525801828354","result":"Success","api_id":"5a84873bd82571518634811","status":"unStatus","api_query":"","daily_limited":"60000","api_member_pack":"Gold member","current_api_version":"3.1","item":[null]}

Please fix, thanks

**Comment by smowtion** [comment]
Issue fixed . Please don't share your api key here
