### ISSUE TITLE
Support for music4you.hu

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#32]
Please provide link check API support for music4you.hu

www.music4you.hu/download/163718/valentino_khan_ft_sean_paul_gold_justin_quiles_remix/
www.music4you.hu/download/163719/valentino_khan_ft_sean_paul_gold_perto_remix/
www.music4you.hu/download/162863/nato_medrado_small_room_tinlicker_extended_remix/
www.music4you.hu/download/163618/edx_jaded/
www.music4you.hu/download/163798/dropgun_krishna/

**Comment by smowtion** [comment]
Done
