### ISSUE TITLE
Support for minhateca.com.br

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#33]
Please provide support for minhateca.com.br

minhateca.com.br/move/MaxiMusic+Pop+Oldies+B+2+-+Bee+Gees+*2c+Billy+Joel+*2c+Bing+Crosby+*2c+Blondie+*26+MORE/Bee+Gees+-+I+Started+A+Joke,180073494.mp3(audio)

minhateca.com.br/andre.clementel/Musica/Int+-+Dance+70*27s/Bee+Gees+-+Tragedy+*5b1978*5d,1138638396.mp3(audio)

minhateca.com.br/carlosalbertoms/Documentos/M*c3*basicas+(MP3)/CDs+Prontos/Bee+Gees+(2010+-+Mythology)/0105_Bee+Gees+-+Tragedy,639321138.mp3(audio)

minhateca.com.br/erica.jbg/M*c3*basicas/Outras/The+Bee+Gees+-+I+Started+A+Joke,382201185.mp3(audio)

minhateca.com.br/Clistovam/M*c3*basicas/Bee+Gees+-+I+Started+a+Joke,546685891.mp3(audio)
minhateca.com.br/totoria/Documentos/Musica/B/Bee+Gees+-+Tragedy,649169010.mp3(audio)
minhateca.com.br/primuschin/Musicas/MUSICAS+SERTANEJAS/MUSICAS+SNJ/Musicas+do+Gogear+2011/GOOD+TIMES+-BONS+TEMPOS/Bee+Gees+-+I+Started+A+Joke,681132306.mp3(audio)

**Comment by smowtion** [comment]
Can you send me a working link ?

**Comment by hurtn** [comment]
Here we go 

minhateca.com.br/zAthena/Music/Zara+Larsson/So+Good

**Comment by smowtion** [comment]
Thank @hurtn , minhateca has added to URLC
