### ISSUE TITLE
Incorrect status for Hulkshare.com

### ISSUE THREAD

**Issue by hurtn** [Thomanphan/urlchecker#34]
Link is marked as working/success but is dead

www.hulkshare.com/2y8ow6u279vk

Thanks

**Comment by smowtion** [comment]
This is file is working

**Comment by hurtn** [comment]
Hello, we see that the file has been disabled - see screenshot attached. The API still says status working. Thanks

![screen shot 2018-03-26 at 10 28 59](https://user-images.githubusercontent.com/5063077/37898395-9da74d2c-30e0-11e8-92ff-91896094f8d5.png)

**Comment by hurtn** [comment]
Here is another one if you need
http://www.hulkshare.com/ubmurda/10-acapella-eminem-bagpipes-from-baghdad

**Comment by smowtion** [comment]
Thank, Issue has fixed.

**Comment by hurtn** [comment]
Great, thank you!!
