### ISSUE TITLE
Rockfile.eu

### ISSUE THREAD

**Issue by grimace1979** [Thomanphan/urlchecker#5]
This link was shown as "dead" when it was "alive" - http://rockfile.eu/t09jqucb57i7.html - Is the checking for Rockfile.eu broken?

**Comment by Thomanphan** [comment]
http://rockfile.eu/ has using cloudflare and blocked with captach, On this time I no solution fix this

**Comment by Thomanphan** [comment]
rockfile.eu has by passed
